/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Base_msg, Base_msg, AUTO)


PB_BIND(Control_msg, Control_msg, AUTO)


PB_BIND(Config_msg, Config_msg, AUTO)


PB_BIND(Ack_msg, Ack_msg, AUTO)


PB_BIND(Generator_Config_msg, Generator_Config_msg, AUTO)


PB_BIND(Const_Freq, Const_Freq, AUTO)


PB_BIND(Freq_Mod, Freq_Mod, AUTO)


PB_BIND(Phase_Mod, Phase_Mod, AUTO)


PB_BIND(Demodulator_config_msg, Demodulator_config_msg, AUTO)


PB_BIND(Debug_msg, Debug_msg, 8)






